### PR TITLE
Levenshtein updates

### PR DESCRIPTION
**Pull request by jeffudall**
Updated Levenshtein files - most notably:
 - added README files to main folder and code folder
 - added leven executable source code (main.cpp) to code folder.

 This time for realsies hopefully

### CODE REVIEW

**Comment by jackwadden** [comment]
Can you move the ./Levenshtein/patternstrings directory to code so it looks like ./Levenshtein/code/patternstrings?

**Comment by jackwadden** [comment]
Looks good. Thanks!

**Comment by jeffudall** [comment]
Okay, did that!

**Comment by jeffudall** [comment]
No prob! :)

**Pull request merged**
