### PR TITLE
Hamming Documentation Update

### PR DESCRIPTION
**Pull request by lemons2lemonade**
Hey Jack, 
I fixed all the typos that I can see, and I think its ready to be merged. Let me know what you think.

### CODE REVIEW

**Comment by jackwadden** [comment]
Could you also add in code to generate Hamming automata and descriptions of how to use that code?

**Comment by lemons2lemonade** [comment]
Sure! I'm guessing that I'll need to use some commands in the script that I
make to generate the automata after I write the necessary c++. Does it
sound like a good idea to use the vasim code you showed me yesterday as a
starting point for this and bulk it up to handle the hamming algos in order
to make the automata like the application wants? Does that sound like a
good approach? If not, let me know what direction you think would be best
to start in and I'll get started.

**Comment by jackwadden** [comment]
Looks great! Can you add a short README.md for how to use the scripts? You did a great job with the usage but would be nice to also have a GitHub landing page for this app.

**Comment by jackwadden** [comment]
Awesome. Looks great. Merging now.

**Pull request merged**
